Track the local commits in addition to the uncommitted changes

diff --git a/git-sync-changes b/git-sync-changes
--- a/git-sync-changes
+++ b/git-sync-changes
@@ -31,7 +31,7 @@ check_remote() {
 }
 
 remote="${1:-origin}"
-user="${2:-$(current_user)}"
+client_name="${2:-$(current_user)/$(current_branch)}"
 branch="${3:-$(current_branch)}"
 
 if [ -z "$(current_head)" ]; then
@@ -40,19 +40,100 @@ if [ -z "$(current_head)" ]; then
 fi
 check_remote "${remote}" || exit 0
 
-local_sync_ref() {
-  echo "refs/sync/${user}/${branch}"
+local_commits_ref() {
+  echo "refs/synced_client/${client_name}"
 }
 
-remote_sync_ref() {
-  echo "refs/sync_remotes/${remote}/${user}/$(current_branch)"
+remote_commits_ref() {
+  echo "refs/synced_remote_client/${remote}/${client_name}"
 }
 
-read_remote_branch() {
-  git ls-remote --heads ${remote} ${branch} | cut -d $'\t' -f 1
+local_changes_ref() {
+  echo "refs/synced_changes/${client_name}"
 }
 
-# Make the local file system match the file tree in the commit at refs/sync/${user}/${branch}.
+remote_changes_ref() {
+  echo "refs/synced_remote_changes/${remote}/${client_name}"
+}
+
+pull_remote_commit() {
+  git fetch "${remote}" "+$(local_commits_ref):$(remote_commits_ref)" 2>/dev/null >&2
+  git fetch "${remote}" "+$(local_changes_ref):$(remote_changes_ref)" 2>/dev/null >&2
+
+  remote_commit="$(git show-ref $(remote_commits_ref) | cut -d ' ' -f 1)"
+  if [ -z "${remote_commit}" ]; then
+    # There is no remote commit to merge
+    return 0
+  fi
+
+  local_commit="$(git show-ref $(local_commits_ref) | cut -d ' ' -f 1)"
+  if [ -z "${local_commit}" ]; then
+    if [ -n "$(git status --porcelain=1)" ]; then
+      # There are local changes that we do not know how to sync
+      echo "Changes to the local client conflict with the remote client" >&2
+      return 1
+    fi
+    git update-ref "$(local_commits_ref)" "$(remote_commits_ref)" 2>/dev/null >&2
+    git update-ref "$(current_branch)" "${remote_commit}^1" 2>/dev/null >&2
+    git checkout HEAD 2>/dev/null >&2
+    return 0
+  fi
+
+  git merge-base --is-ancestor "${remote_commit}" "${local_commit}" 2>/dev/null >&2
+  if [ "$?" == "0" ]; then
+    # We have already merged the remote commits
+    return 0
+  fi
+
+  git merge-base --is-ancestor "${local_commit}" "${remote_commit}"  2>/dev/null >&2
+  if [ "$?" == "0" ]; then
+    if [ -n "$(git status --porcelain=1)" ]; then
+      # There are obsolete local changes that we do need to clear out
+      git reset HEAD ./ 2>/dev/null >&2
+      git checkout -- ./ 2>/dev/null >&2
+    fi
+    git update-ref "$(local_commits_ref)" "$(remote_commits_ref)" 2>/dev/null >&2
+    git update-ref "$(current_branch)" "${remote_commit}^1" 2>/dev/null >&2
+    git checkout HEAD 2>/dev/null >&2
+    return 0
+  fi
+
+  # We have conflicting updates to the client, and the user must manually fix them
+  echo "Conflicting local and remote clients" >&2
+  return 1
+}
+
+# Save the current, committed state of the local client.
+#
+# The resulting commit forms a history of every commit (including rebases)
+# that the local client has made to the current branch since that local
+# branch was created.
+save_current_commit() {
+  previous_commits="$(git show-ref $(local_commits_ref) | cut -d ' ' -f 1)"
+  committed_tree=$(git cat-file -p "$(current_branch)" | head -n 1 | cut -d ' ' -f 2)
+  if [ -z "${previous_commits}" ]; then
+    merged_commit=$(git commit-tree -p "$(current_branch)" -m "Save local commits" "${committed_tree}")
+    git update-ref "$(local_commits_ref)" "${merged_commit}" 2>/dev/null >&2
+  fi
+  git merge-base --is-ancestor "$(current_branch)" "$(local_commits_ref)" 2>/dev/null >&2
+  if [ "$?" != "0" ]; then
+    # The local branch has been updated since we last saved the committed state.
+    # We need to update the commits ref to include this change in our history.
+    merged_commit=$(git commit-tree -p "$(current_branch)" -p "$(local_commits_ref)" -m "Save local commits" "${committed_tree}")
+    git update-ref "$(local_commits_ref)" "${merged_commit}" 2>/dev/null >&2
+  fi
+}
+
+push_current_commit() {
+  remote_commit="$(git show-ref $(remote_commits_ref) | cut -d ' ' -f 1)"
+  git push "${remote}" --force-with-lease="$(local_commits_ref):${remote_commit}" "$(local_commits_ref):$(local_commits_ref)" 2>/dev/null >&2
+  if [ "$?" != "0" ]; then
+    echo "Failed to push the committed local client state to the remote" >&2
+    return 1
+  fi
+}
+
+# Make the local file system match the file tree in the commit at $(local_changes_ref).
 #
 # This is the logical inverse of `save_changes`
 replay_changes() {
@@ -62,7 +143,7 @@ replay_changes() {
   cd "${tempdir}"
   tempbranch="$(current_branch)"
 
-  git checkout "$(local_sync_ref)" 2>/dev/null >&2
+  git checkout "$(local_changes_ref)" 2>/dev/null >&2
   for dir in `find ./ -not -path './.git/*' -and -not -name '.git' -and -type d`; do
     mkdir -p "${maindir}/${dir}"
   done
@@ -84,32 +165,23 @@ replay_changes() {
 # Merge saved changes from the remote to our local changes.
 #
 # This method enforces the following constraints; after the method returns.
-# 1. The commit at refs/sync/${user}/${branch} (if it exists) contains all
+# 1. The commit at $(local_changes_ref) (if it exists) contains all
 #    changes that were made either locally or remotely after the branch was
 #    changed to its current value.
 # 2. The local client's files (except for ignored files) match the tree
-#    in the commit at refs/sync/${user}/${branch} (if it exists).
-fetch_remote_changes() {
-  remote_branch="$(read_remote_branch)"
-  if [ "${remote_branch}" != "$(current_head)" ]; then
-    # Our branch is not in sync with the remote,
-    # so do not try to sync the change histories.
-    return 1
-  fi
-  
-  local_ref="$(local_sync_ref)"
-  remote_ref="$(remote_sync_ref)"
-
-  git fetch "${remote}" "+${local_ref}:${remote_ref}" 2>/dev/null >&2 || git update-ref -d "${remote_ref}"
+#    in the commit at $(local_changes_ref) (if it exists).
+merge_remote_changes() {
+  local_ref="$(local_changes_ref)"
+  remote_ref="$(remote_changes_ref)"
   local_commit="$(git show-ref ${local_ref} | cut -d ' ' -f 1)"
   remote_commit="$(git show-ref ${remote_ref} | cut -d ' ' -f 1)"
 
   if [ -z "${remote_commit}" ]; then
-    # There are no remote changes to pull down.
+    # There are no remote changes to merge.
     return 0
   fi
 
-  git merge-base --is-ancestor "${branch}" "${remote_commit}" 2>/dev/null >&2
+  git merge-base --is-ancestor "$(local_commits_ref)" "${remote_commit}" 2>/dev/null >&2
   if [ "$?" != "0" ]; then
     # The remote changes are out of date, so do not pull them down.
     # (But still allow our local, up to date changes to be pushed back)
@@ -119,7 +191,7 @@ fetch_remote_changes() {
   if [ -z "${local_commit}" ]; then
     # We have no local modifications, so copy the remote ones as-is
     git update-ref "${local_ref}" "${remote_commit}" 2>/dev/null >&2
-    diff="$(git diff ${branch}..${remote_commit})"
+    diff="$(git diff $(local_commits_ref)..${remote_commit})"
     if [ -n "${diff}" ]; then
       echo "${diff}" | git apply --
     fi
@@ -170,8 +242,8 @@ fetch_remote_changes() {
 }
 
 push_local_changes() {
-  local_ref="$(local_sync_ref)"
-  remote_ref="$(remote_sync_ref)"
+  local_ref="$(local_changes_ref)"
+  remote_ref="$(remote_changes_ref)"
   remote_commit="$(git show-ref ${remote_ref} | cut -d ' ' -f 1)"
 
   if [ -z "$(git show-ref ${local_ref})" ]; then
@@ -189,43 +261,42 @@ push_local_changes() {
 # This differs from `git stash` in that multiple changes can
 # be chained together.
 #
-# The resulting commit is stored in refs/sync/${user}/${branch}
+# The resulting commit is stored in $(local_changes_ref)
 #
 # This method enforces two constraints; after the method returns:
 # 1. The contents of the local client's files (other than ignored files)
-#    matches the tree of the commit stored at refs/sync/${user}/${branch},
+#    matches the tree of the commit stored at $(local_changes_ref),
 #    if it exists.
-# 2. The history of the commit stored at refs/sync/${user}/${branch},
-#    if it exists, includes every change that was saved since ${branch}
+# 2. The history of the commit stored at $(local_changes_ref),
+#    if it exists, includes every change that was saved since HEAD
 #    was changed to its current value.
 save_changes() {
-  local_ref="$(local_sync_ref)"
-  local_commit="$(git show-ref ${local_ref} | cut -d ' ' -f 1)"
-  if [ -n "${local_commit}" ]; then
-    git merge-base --is-ancestor "${branch}" "${local_ref}" 2>/dev/null >&2
+  saved_changes_commit="$(git show-ref $(local_changes_ref) | cut -d ' ' -f 1)"
+  if [ -n "${saved_changes_commit}" ]; then
+    git merge-base --is-ancestor "$(local_commits_ref)" "$(local_changes_ref)" 2>/dev/null >&2
     if [ "$?" != "0" ]; then
       # The local branch has been updated since our last save. We need
       # to clear out the (now obsolete) saved changes.
-      git update-ref -d "${local_ref}"
-      local_commit=""
+      git update-ref -d "$(local_changes_ref)"
+      saved_changes_commit=""
     fi
   fi
 
   current_changes="$(git status --porcelain=1)"
-  if [ -z "${local_commit}" ] && [ -z "${current_changes}" ]; then
+  if [ -z "${saved_changes_commit}" ] && [ -z "${current_changes}" ]; then
     # We have neither local modifications nor previously saved changes
     return 0
   fi
   if [ -z "${current_changes}" ]; then
     # We undid previous changes, so we need to create a commit to record that
-    changes_tree=$(git cat-file -p "${branch}" | head -n 1 | cut -d ' ' -f 2)
-    changes_commit=$(git commit-tree -p "${local_commit}" -m "Save local changes" "${changes_tree}")
-    git update-ref "${local_ref}" "${changes_commit}" 2>/dev/null >&2
+    changes_tree=$(git cat-file -p "$(local_commits_ref)" | head -n 1 | cut -d ' ' -f 2)
+    changes_commit=$(git commit-tree -p "${saved_changes_commit}" -m "Save local changes" "${changes_tree}")
+    git update-ref "$(local_changes_ref)" "${changes_commit}" 2>/dev/null >&2
     return 0
   fi
 
-  if [ -z "${local_commit}" ]; then
-    local_commit="${branch}"
+  if [ -z "${saved_changes_commit}" ]; then
+    saved_changes_commit="$(local_commits_ref)"
   fi
 
   # Create a temporary directory in which to create the changes commit
@@ -242,12 +313,12 @@ save_changes() {
   tempbranch="$(current_branch)"
   git add ./
 
-  if [ -n "$(git diff ${local_commit} -- ./)" ]; then
+  if [ -n "$(git diff ${saved_changes_commit} -- ./)" ]; then
     # We have changes since the last time we saved.
     git commit -a -m "Save local changes" 2>/dev/null >&2
     changes_tree=$(git cat-file -p "${tempbranch}" | head -n 1 | cut -d ' ' -f 2)
-    changes_commit=$(git commit-tree -p "${local_commit}" -m "Save local changes" "${changes_tree}")
-    git update-ref "${local_ref}" "${changes_commit}" 2>/dev/null >&2
+    changes_commit=$(git commit-tree -p "${saved_changes_commit}" -m "Save local changes" "${changes_tree}")
+    git update-ref "$(local_changes_ref)" "${changes_commit}" 2>/dev/null >&2
   fi
 
   # Cleanup post merge
@@ -257,6 +328,9 @@ save_changes() {
   git worktree prune
 }
 
+pull_remote_commit || exit 1
+save_current_commit 
+push_current_commit || exit 1
 save_changes
-fetch_remote_changes || exit 0
+merge_remote_changes || exit 0
 push_local_changes
